import "server-only";
import { db, type User } from "@/db";
import { brandFor } from "./brand";
import { fmtDate, periodLabel, ugx } from "./format";
import { PdfWriter, embedLogo } from "./pdf";

const METHODS: Record<string, string> = { mtn: "MTN Mobile Money", airtel: "Airtel Money", cash: "Cash", bank: "Bank transfer" };

/**
 * Everything a rent receipt shows, from the ledger itself: each charge the payment settled (with the period it
 * covers, as the Landlord and Tenant Act s.25 requires), any amount kept as credit, and the balance left.
 */
export async function receiptData(paymentId: number, viewer?: User) {
  const p = await db.payment.findUnique({
    where: { id: paymentId },
    include: {
      allocations: { include: { charge: true }, orderBy: { id: "asc" } },
      charge: true,
      recordedBy: { select: { name: true } },
      lease: { include: { tenant: true, landlord: true, unit: { include: { property: true } } } },
    },
  });
  if (!p || p.status !== "success") return null;
  if (viewer && viewer.role !== "manager" && viewer.id !== p.lease.tenantId && viewer.id !== p.lease.landlordId) return null;
  const lines = p.allocations.map((a) => ({
    description: a.charge.description,
    period: /^\d{4}-\d{2}$/.test(a.charge.period) ? periodLabel(a.charge.period) : a.charge.kind === "deposit" ? "Security deposit" : `Due ${fmtDate(a.charge.dueDate)}`,
    amount: a.amount,
  }));
  if (!lines.length) lines.push({ description: p.charge.description, period: periodLabel(p.charge.period), amount: p.amount });
  const applied = lines.reduce((s, l) => s + l.amount, 0);
  const credit = Math.max(0, p.amount - applied);
  const open = await db.charge.findMany({ where: { leaseId: p.leaseId, status: { not: "paid" } }, select: { amount: true, paid: true } });
  const balance = open.reduce((s, c) => s + c.amount - c.paid, 0);
  const brand = await brandFor(p.lease.landlordId);
  return {
    p, brand, lines, credit, balance,
    tenant: p.lease.tenant, landlord: p.lease.landlord,
    property: p.lease.unit.property.name, unit: p.lease.unit.label, address: p.lease.unit.property.location,
    method: METHODS[p.method] ?? p.method, recordedBy: p.recordedBy?.name ?? null,
  };
}
export type ReceiptData = NonNullable<Awaited<ReturnType<typeof receiptData>>>;

export async function receiptPdf(r: ReceiptData) {
  const w = await PdfWriter.create({ accent: r.brand.accentColor, title: `Receipt ${r.p.receiptNo}`, author: r.brand.displayName, footer: r.brand.showCasaVilla ? "Generated by CasaVilla Property Management" : r.brand.displayName });
  // Header: logo left, issuer details right
  const top = w.y;
  const logo = await embedLogo(w, r.brand.logoFileId);
  if (logo) w.image(logo, 150, 60);
  w.y = top;
  const right = w.W / 2;
  w.text(r.brand.displayName, { x: right, size: 11, bold: true, align: "right" });
  for (const l of [r.brand.address, r.brand.phone, r.brand.email, r.brand.tin && `TIN: ${r.brand.tin}`].filter(Boolean) as string[]) w.text(l, { x: right, size: 8.5, color: undefined, align: "right" });
  w.y = Math.min(w.y, top - 70); w.rule(w.accent);

  w.text("PAYMENT RECEIPT", { size: 9, bold: true, color: w.accent });
  w.text(r.p.receiptNo ?? "", { size: 20, bold: true });
  w.gap(4);
  w.facts([
    ["Date paid", fmtDate(r.p.paidAt)], ["Payment method", `${r.method}${r.p.phone ? ` · ${r.p.phone}` : ""}`],
    ["Received from", `${r.tenant.name} · ${r.tenant.phone}`], ["Property", `${r.property} · ${r.unit}`],
    ["Landlord", r.landlord.name], ["Reference", r.p.reference],
  ]);
  w.gap(6);
  w.table(["Description", "Period covered", "Amount"], r.lines.map((l) => [l.description, l.period, ugx(l.amount)]), {
    widths: [230, 150, 119.28],
    totalRows: [
      ...(r.credit ? [["Kept as credit for upcoming rent", "", ugx(r.credit)]] : []),
      ["Total paid", "", ugx(r.p.amount)],
      ["Balance still owed on this tenancy", "", ugx(r.balance)],
    ],
  });
  w.gap(10);
  if (r.brand.footerNote) w.text(r.brand.footerNote, { size: 9, italic: true });
  if (r.recordedBy) w.text(`Recorded by ${r.recordedBy}.`, { size: 8, color: undefined });
  w.signature([{ label: r.brand.signatoryTitle || `For ${r.brand.displayName}`, name: r.brand.signatory ?? undefined }]);
  w.gap(6);
  w.text("Issued electronically in line with section 25 of the Landlord and Tenant Act, 2022. Keep this receipt for your records.", { size: 7.5 });
  return w.bytes();
}
