import { FileButton } from "./FileButton";
import { db } from "@/db";
import { brandFor, CASAVILLA } from "@/lib/brand";
import { saveBrand } from "@/app/doc-actions";
import { Field } from "./ui";
import { Submit, FileInput } from "./client";

/** Receipt & agreement look for one landlord (ownerId) or CasaVilla's default (no ownerId). */
export async function BrandForm({ ownerId, sampleReceiptId }: { ownerId?: number | null; sampleReceiptId?: number | null }) {
  const own = await db.brandProfile.findFirst({ where: { ownerId: ownerId ?? null } });
  // A landlord starts from their own details (not CasaVilla's address and phone).
  const owner = ownerId ? await db.user.findUnique({ where: { id: ownerId }, select: { name: true, phone: true, email: true } }) : null;
  const b = own ?? (owner
    ? { ...(await brandFor(null)), displayName: owner.name, phone: owner.phone, email: owner.email, address: null, tin: null, signatory: owner.name, signatoryTitle: "Landlord", logoFileId: null }
    : CASAVILLA);
  return (
    <form action={saveBrand} className="card space-y-4">
      {ownerId && <input type="hidden" name="ownerId" value={ownerId} />}
      <div>
        <div className="h2">Receipts &amp; agreements</div>
        <p className="muted">How your receipts, tenancy agreements and booking confirmations look — on screen, in PDFs and in emails.</p>
      </div>
      <div className="grid gap-3 sm:grid-cols-2">
        <Field label="Name on documents"><input name="displayName" defaultValue={b.displayName} className="input" required maxLength={120} /></Field>
        <Field label="TIN (optional)"><input name="tin" defaultValue={b.tin ?? ""} className="input" maxLength={30} placeholder="URA TIN" /></Field>
        <Field label="Address"><input name="address" defaultValue={b.address ?? ""} className="input" maxLength={200} /></Field>
        <Field label="Phone"><input name="phone" defaultValue={b.phone ?? ""} className="input" maxLength={80} /></Field>
        <Field label="Email"><input name="email" type="email" defaultValue={b.email ?? ""} className="input" maxLength={120} /></Field>
        <Field label="Brand colour"><input name="accentColor" type="color" defaultValue={b.accentColor} className="input h-12 p-1" /></Field>
        <Field label="Signed by (name)"><input name="signatory" defaultValue={b.signatory ?? ""} className="input" maxLength={100} /></Field>
        <Field label="Signatory title"><input name="signatoryTitle" defaultValue={b.signatoryTitle ?? ""} className="input" maxLength={100} placeholder="e.g. Property Manager" /></Field>
      </div>
      <Field label="Footer note on receipts"><input name="footerNote" defaultValue={b.footerNote ?? ""} className="input" maxLength={300} placeholder="e.g. Rent is due by the 5th. Thank you!" /></Field>
      <Field label={b.logoFileId ? "Replace logo (PNG or JPG)" : "Your logo (PNG or JPG, optional)"}><FileInput name="logo" accept="image/png,image/jpeg" /></Field>
      {b.logoFileId && (
        <div className="flex items-center gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={`/api/files/${b.logoFileId}`} alt="Current logo" className="h-10 w-auto rounded" />
          <label className="flex items-center gap-2 text-sm text-stone-600"><input type="checkbox" name="removeLogo" className="accent-brand-700" /> Use the CasaVilla logo instead</label>
        </div>
      )}
      <label className="flex items-center gap-2 text-sm text-stone-600"><input type="checkbox" name="showCasaVilla" defaultChecked={b.showCasaVilla} className="h-4 w-4 accent-brand-700" /> Show “Generated by CasaVilla” in the footer</label>
      <div className="flex flex-wrap gap-2">
        <Submit>Save</Submit>
        {sampleReceiptId && <FileButton href={`/receipts/${sampleReceiptId}/pdf`} name="Sample-receipt.pdf" className="btn-outline">Get a sample receipt PDF</FileButton>}
      </div>
    </form>
  );
}
